### ISSUE TITLE
Looks great, but fails immediately at 'make setup' because it asserts Pro access to Fontawesome

### ISSUE THREAD

**Issue by desrod** [jimmysawczuk/power-monitor#9]
Would be great to reconfigure this not to require a Pro account on Fontawesome, fails straight away because of the yarn.lock declarations and dependencies on fontawesome-pro. Shame, it looked like a promising project! 

There's a few other stumbling blocks as well: 

1. 'make tls', claims it succeeds, even when it fails (because 'mkcert' isn't found, installed or available)
2. 'make release' fails for a similar reason ('scm-status' not found, not sure what that is, but it's nowhere to be found in any package in any repository)

I'm muddling my way through, but it's a handful of stumbling blocks.

**Comment by jimmysawczuk** [comment]
Thanks for the feedback! I haven't looked at this project in a little while, but I'm happy to accept PRs! I'm definitely open to removing the Fontawesome Pro dependency (or making it optional) and I'm definitely sure the docs can use some work.  

`mkcert` is https://github.com/FiloSottile/mkcert, and `scm-status` is https://github.com/jimmysawczuk/scm-status. You're right; those requirements should absolutely be documented better. But `mkcert` is really just for local development, and `scm-status` is only used when building release binaries; maybe the solution here is to just build the binaries and release them here?

**Comment by desrod** [comment]
I quite literally only received my RMCARD205 this afternoon, so was looking for a better way to get at the stats, data, graphs, and came across your project. It looked the most appealing, workable, but I started tripping on branches right from the start. 

I'm happy to get in there and issue some PRs, no problem at all. I'll probably start with pulling out the FA dependency, and have the Makefile do some sanity checking ($GOPATH, make sure bins it refers to are in $PATH before calling them and erroring out, etc.) 

But before I start pulling pieces apart and gluing them back together, did you have any other plans/design goals for this that I should know before submitting fixes? 

Thanks for the quick response!

**Comment by jimmysawczuk** [comment]
My main design goal right now is to keep the entire application as one binary. For the future I'm exploring decoupling the data collection from the processing and reporting APIs as well as the frontend. But that's definitely not a near-term thing.

**Comment by jimmysawczuk** [comment]
Closing this out as there are now prebuilt binaries available here: https://github.com/jimmysawczuk/power-monitor/releases.
